# Generated by Django 6.1.1 on 2026-10-03 10:40

from django.db import migrations, models


def normalize_statuses(apps, schema_editor):
    Complaint = apps.get_model('complaints', 'Complaint')
    using = schema_editor.connection.alias
    for old, new in (
        ('open', 'OPEN'),
        ('in_progress', 'IN_PROGRESS'),
        ('resolved', 'RESOLVED'),
        ('closed', 'CLOSED'),
    ):
        Complaint.objects.using(using).filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='staff_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.RunPython(normalize_statuses, migrations.RunPython.noop),
    ]
