# Generated by Django 6.1.1 on 2026-10-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_resolved_date_complaint_staff_response_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='assigned_to',
            new_name='assigned_staff',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='subject',
            new_name='title',
        ),
    ]
