# Generated by Django 6.1.1 on 2026-09-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_size',
            field=models.CharField(choices=[('500ml', '500 ml'), ('1.5l', '1.5 litres'), ('5l', '5 litres'), ('10l', '10 litres'), ('20l', '20 litres')], default='500ml', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sachet', 'Sachet Water'), ('bottled', 'Bottled Water'), ('dispenser', 'Dispenser Water'), ('other', 'Other')], default='bottled', max_length=20),
        ),
    ]
