# Generated by Django 6.1.1 on 2026-09-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_day3_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
