# Generated by Django 6.1.1 on 2026-09-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening Stock'), ('in', 'Stock Received'), ('out', 'Stock Issued'), ('damaged', 'Damaged'), ('returned', 'Returned'), ('adjustment', 'Adjustment')], max_length=12),
        ),
    ]
