# Generated by Django 6.1.1 on 2026-09-30 14:59

from django.db import migrations, models


def restore_legacy_activity(apps, schema_editor):
    vehicle_model = apps.get_model('deliveries', 'Vehicle')
    vehicle_model.objects.exclude(status='active').update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_remove_vehicle_is_active_delivery_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(restore_legacy_activity, migrations.RunPython.noop),
    ]
