# Generated by Django 6.1.1 on 2026-10-01 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_vehicle_is_active'),
        ('orders', '0002_remove_orderitem_unique_product_per_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('PARTIALLY_DELIVERED', 'Partially delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=30),
        ),
    ]
