# Generated by Django 6.1.1 on 2026-09-26 06:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def populate_order_totals(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')

    for order in Order.objects.all().iterator():
        order.order_reference = f'ORD-{order.pk:05d}'
        if order.status == 'processing':
            order.status = 'preparing'
        order.save(update_fields=['order_reference', 'status'])

    for item in OrderItem.objects.all().iterator():
        item.subtotal = Decimal(item.quantity) * item.unit_price
        item.save(update_fields=['subtotal'])

    for order in Order.objects.all().iterator():
        total = sum(order.items.values_list('subtotal', flat=True), Decimal('0.00'))
        Order.objects.filter(pk=order.pk).update(total_amount=total)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_product_per_order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_reference',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('partially_delivered', 'Partially Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.RunPython(populate_order_totals, migrations.RunPython.noop),
    ]
